// Mocks generated by Mockito 5.3.2 from annotations
// in oracle_rm/test/core/characters/data/datasources/characters_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oracle_rm/core/characters/data/datasources/characters_remote_datasource.dart'
    as _i3;
import 'package:oracle_rm/core/characters/data/models/character.dart' as _i5;
import 'package:oracle_rm/core/characters/data/models/models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCharacterDetailsModel_0 extends _i1.SmartFake
    implements _i2.CharacterDetailsModel {
  _FakeCharacterDetailsModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CharactersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharactersRemoteDataSource extends _i1.Mock
    implements _i3.CharactersRemoteDataSource {
  MockCharactersRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.CharacterModel>> getAllCharacters() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCharacters,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.CharacterModel>>.value(<_i5.CharacterModel>[]),
      ) as _i4.Future<List<_i5.CharacterModel>>);
  @override
  _i4.Future<_i2.CharacterDetailsModel> getCharacterDetails({
    required String? id,
    required List<String>? episodesIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterDetails,
          [],
          {
            #id: id,
            #episodesIds: episodesIds,
          },
        ),
        returnValue: _i4.Future<_i2.CharacterDetailsModel>.value(
            _FakeCharacterDetailsModel_0(
          this,
          Invocation.method(
            #getCharacterDetails,
            [],
            {
              #id: id,
              #episodesIds: episodesIds,
            },
          ),
        )),
      ) as _i4.Future<_i2.CharacterDetailsModel>);
}
