name: oracle_rm
description: THA Loft

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Object properties equality comparison
  equatable: 2.0.5
  # Functional programming
  dartz: 0.10.1
  # Files generator
  build_runner: 2.3.2

  # GraphQL Client
  graphql: 5.1.1

  # Local Storage
  shared_preferences: 2.0.15

  # UI state management
  flutter_bloc: 8.1.1

  # Service Locator
  get_it: 7.2.0

  # App routing
  go_router: 5.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  mockito: 5.3.2

flutter:
  uses-material-design: true
