name: oracle_rm
description: THA Loft

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Object properties equality comparison
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: 5.3.2

flutter:
  uses-material-design: true
