// Mocks generated by Mockito 5.3.2 from annotations
// in oracle_rm/test/core/favorites/domain/repositories/favorites_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:oracle_rm/core/error/error.dart' as _i5;
import 'package:oracle_rm/core/favorites/domain/repositories/favorites_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavoritesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesRepository extends _i1.Mock
    implements _i3.FavoritesRepository {
  MockFavoritesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, List<String>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppError, List<String>>>.value(
            _FakeEither_0<_i5.AppError, List<String>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, List<String>>>);
  @override
  _i4.Future<_i2.Either<_i5.AppError, bool>> update(
          {required String? characterId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#characterId: characterId},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppError, bool>>.value(
            _FakeEither_0<_i5.AppError, bool>(
          this,
          Invocation.method(
            #update,
            [],
            {#characterId: characterId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, bool>>);
}
