// Mocks generated by Mockito 5.3.2 from annotations
// in oracle_rm/test/core/favorites/data/datasources/favorites_local_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:oracle_rm/core/favorites/data/datasources/favorites_local_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoritesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesLocalDataSource extends _i1.Mock
    implements _i2.FavoritesLocalDataSource {
  MockFavoritesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  _i3.Future<bool> save({required String? characterId}) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
          {#characterId: characterId},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> remove({required String? characterId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {#characterId: characterId},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
